[package]
name = "gaia"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.2", features = ["derive"] }
console = "0.15.8"
dialoguer = "0.11.0"
reqwest = { version = "0.11", features = ["blocking"] }
tokio = { version = "1", features = ["full"] }
